### ISSUE TITLE
Etherscan doesn't display contract functions

### ISSUE THREAD

**Issue by Trisome-Bedrock** [Bedrock-Technology/bedrock-dao#35]
Contract information on Etherscan is unreadable for certain contracts, such as [GaugeController](https://goerli.etherscan.io/address/0xa64B2dFfA8818E4A931e7B25ABDDB4CeA12777B4#readContract), [VotingEscrow](https://goerli.etherscan.io/address/0x19Cd39eC64d3AbbcF9A448175400cDDbA97B9f56#readContract), [VeRewards](https://goerli.etherscan.io/address/0xFEB5317b7cAA5d88929f60a5fe8481cFa9854f9e#readContract), [PenpieAdapter](https://goerli.etherscan.io/address/0x8e569500a0BD5409Ba75945D01Bc77aBF12021f3#readContract), [Cashier](https://goerli.etherscan.io/address/0xC727b69476359ee3B9fecD3d82b0cB8ef01BC7FC), [BribeManager](https://goerli.etherscan.io/address/0x39889AA0e56AB15E17bB4AEeCa8f2809cDC11006#readContract).

**Comment by aayush-bedrock** [comment]
SInce this was an issue with the goerli testnet, I'm closing this issue
